version: '3'

services:
  mio:
    image: theteamaker/mio
    environment:
      - TOKEN=<secret>
      - PREFIX="mio "
      - SQL_DATABASE="sqlite:///data/database.db"
    volumes:
      - mio_data:/app/data

volumes:
  mio_data:
    external: true